// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vculp.Api.Data.EntityFramework;

#nullable disable

namespace Vculp.Api.Data.EntityFramework.Migrations
{
    [DbContext(typeof(CoreContext))]
    [Migration("20230812125134_Add new Vehicle domain")]
    partial class AddnewVehicledomain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vculp.Api.Domain.Core.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ClusterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClusterId"));

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreationTime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ExternalUserId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("LastUpdated")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("ClusterId")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_ClusterId");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("ClusterId"));

                    b.HasIndex("ExternalUserId")
                        .IsUnique();

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Users_IsDeleted");

                    b.HasIndex("MobileNumber")
                        .IsUnique();

                    b.ToTable("Users", "User");
                });

            modelBuilder.Entity("Vculp.Api.Domain.Core.Vehicle.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ClusterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClusterId"));

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreationTime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("LastUpdated")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("VehicleBodyType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("ClusterId")
                        .IsUnique()
                        .HasDatabaseName("IX_Vehicles_ClusterId");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("ClusterId"));

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Vehicles_IsDeleted");

                    b.ToTable("Vehicles", "Vehicle");
                });

            modelBuilder.Entity("Vculp.Api.Domain.Core.Vehicle.Vehicle", b =>
                {
                    b.OwnsMany("Vculp.Api.Domain.Core.Vehicle.FareDetails", "FareDetails", b1 =>
                        {
                            b1.Property<Guid>("VehicleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("ClusterId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("ClusterId"));

                            b1.Property<string>("City")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double>("BaseFare")
                                .HasColumnType("float");

                            b1.Property<double>("CancellationFeePercentage")
                                .HasColumnType("float");

                            b1.Property<double>("CancellationMaxAmount")
                                .HasColumnType("float");

                            b1.Property<double>("FreeKms")
                                .HasColumnType("float");

                            b1.Property<double>("MinPerKmFare")
                                .HasColumnType("float");

                            b1.Property<double>("PerKmFare")
                                .HasColumnType("float");

                            b1.Property<double>("PerMinuteFare")
                                .HasColumnType("float");

                            b1.HasKey("VehicleId", "ClusterId", "City");

                            SqlServerKeyBuilderExtensions.IsClustered(b1.HasKey("VehicleId", "ClusterId", "City"), false);

                            b1.HasIndex("ClusterId")
                                .IsUnique();

                            SqlServerIndexBuilderExtensions.IsClustered(b1.HasIndex("ClusterId"));

                            b1.ToTable("FareDetails", "Vehicle");

                            b1.WithOwner()
                                .HasForeignKey("VehicleId");
                        });

                    b.Navigation("FareDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
