version: '3.7'

services:
  vculp-api:
    image: kennyagrisoft.azurecr.io/winmill/agrisoft.winmill.api:${DOCKERCITAG}
    build:
      context: ./Vculp.Api
      dockerfile: Dockerfile
      args:
        source: "/publish"